#include "TimingAnalyzer.h"

/**
* The format will be:
* [TIMING][WHEN][PRF_ALGORITHM][NUM_BIT_OUTPUT][VALUE_MILLISEC]
* with:
* - TIMING => is a static string (used to differentiate MemoryAnalyzer from TimingAnalyzer)
* - WHEN => START/END
* - PRF_ALGORITHM => HMAC_SHA1/HMAC_SHA256
* - NUM_BIT_OUTPUT => number of bits of the key generated by KDF
* - VALUE_MILLISEC => current millisec. The "mills" function returns the number of milliseconds
* 					  since the Arduino board began running the current program. 
*/
String TimingAnalyzer::getCurrentTime(String when, HMAC_type algorithm, size_t numBitOutputKDF) {

	String buf;
	buf += "[TIMING]";
	buf += "[" + when + "]";

	switch(algorithm){
		case HMAC_SHA1:
    		buf += "[HMAC_SHA1]";
	    break;
	    case HMAC_SHA256:
	    	buf += "[HMAC_SHA256]";
	    break;
	}
	buf += "[" + String(numBitOutputKDF) + "]";
	buf += "[" + String(millis()) + "]";

	Serial.println(buf);

	return buf;

}
